# https://www.andreasnesheim.no/setting-up-ci-for-your-net-maui-ios-app-with-github-actions/
name: MAUI iOS Build IPA

on:
  workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-filepath: 'DistributionCertANesheim.p12'
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

    - name: dotnet publish
      run: dotnet publish -c Release -f:net8.0-ios /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false 
